version: 'latest'
services:
  postgres:
    container_name: postgresql-container-1
    restart: always
    image: postgres
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=assignment2
      - POSTGRES_PASSWORD=somePassword
      - PGDATA=assignment2-data
    volumes: 
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql